# Generated by Django 4.2.5 on 2024-03-12 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastname',
        ),
    ]
