# Generated by Django 5.0.3 on 2024-03-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapi', '0002_remove_users_firstname_remove_users_lastname'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='issue',
            field=models.CharField(default=None, max_length=700, null=True),
        ),
    ]
